### ISSUE TITLE
Error contributing Adobe Illustrator vectors

### ISSUE THREAD

**Issue by chrislitherland95** [Templarian/MaterialDesign#145]
Having issues with the contribution page, which says my image is not 24px. It is certainly 24px, even following the provided templates does not yield successful response from the uploader. I manually set the width= and height= elements in my vector file and the upload is successful, however then my image  only contains a single path, and will not render the finer internal details of the icon.

I would attach but GitHub doesn't support SVG uploads.

**Comment by Templarian** [comment]
Just attach it to one of the many upload sites or paste in the SVG files contents inside of:

    ```
    paste here
    ```

**Comment by Templarian** [comment]
I have Illustrator CC so I can test what export settings do work, but I'll just code it to work with whatever file you give me.

**Comment by chrislitherland95** [comment]
```

<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
<path d="M16,22H8c-1.1,0-2-0.9-2-2V4c0-1.1,0.9-2,2-2h8c1.1,0,2,0.9,2,2v16C18,21.1,17.1,22,16,22z"/>
<rect x="8" y="4" fill="#FFFFFF" width="8" height="2"/>
<rect x="8" y="8" fill="#FFFFFF" width="8" height="2"/>
<circle fill="#FFFFFF" cx="15" cy="19" r="1"/>
</svg>

```

**Comment by chrislitherland95** [comment]
Another one here to compare:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
<path d="M19,21H5c-1.1,0-2-0.9-2-2V5c0-1.1,0.9-2,2-2h14c1.1,0,2,0.9,2,2v14C21,20.1,20.1,21,19,21z"/>
<rect x="15" y="5" fill="#FFFFFF" width="4" height="14"/>
<rect x="5" y="5" fill="#FFFFFF" width="8" height="4"/>
<path fill="#FFFFFF" d="M7,12c0,0.6-0.4,1-1,1l0,0c-0.6,0-1-0.4-1-1l0,0c0-0.6,0.4-1,1-1l0,0C6.6,11,7,11.4,7,12L7,12z"/>
<path fill="#FFFFFF" d="M10,12c0,0.6-0.4,1-1,1l0,0c-0.6,0-1-0.4-1-1l0,0c0-0.6,0.4-1,1-1l0,0C9.6,11,10,11.4,10,12L10,12z"/>
<path fill="#FFFFFF" d="M13,12c0,0.6-0.4,1-1,1l0,0c-0.6,0-1-0.4-1-1l0,0c0-0.6,0.4-1,1-1l0,0C12.6,11,13,11.4,13,12L13,12z"/>
<path fill="#FFFFFF" d="M7,15c0,0.6-0.4,1-1,1l0,0c-0.6,0-1-0.4-1-1l0,0c0-0.6,0.4-1,1-1l0,0C6.6,14,7,14.4,7,15L7,15z"/>
<path fill="#FFFFFF" d="M10,15c0,0.6-0.4,1-1,1l0,0c-0.6,0-1-0.4-1-1l0,0c0-0.6,0.4-1,1-1l0,0C9.6,14,10,14.4,10,15L10,15z"/>
<path fill="#FFFFFF" d="M13,15c0,0.6-0.4,1-1,1l0,0c-0.6,0-1-0.4-1-1l0,0c0-0.6,0.4-1,1-1l0,0C12.6,14,13,14.4,13,15L13,15z"/>
<path fill="#FFFFFF" d="M7,18c0,0.6-0.4,1-1,1l0,0c-0.6,0-1-0.4-1-1l0,0c0-0.6,0.4-1,1-1l0,0C6.6,17,7,17.4,7,18L7,18z"/>
<path fill="#FFFFFF" d="M10,18c0,0.6-0.4,1-1,1l0,0c-0.6,0-1-0.4-1-1l0,0c0-0.6,0.4-1,1-1l0,0C9.6,17,10,17.4,10,18L10,18z"/>
<path fill="#FFFFFF" d="M13,18c0,0.6-0.4,1-1,1l0,0c-0.6,0-1-0.4-1-1l0,0c0-0.6,0.4-1,1-1l0,0C12.6,17,13,17.4,13,18L13,18z"/>
</svg>
```

**Comment by Templarian** [comment]
I see what is wrong. First of all everything needs to be combined to a single path. Select all your objects and click the `unite`. for the path.

The other issue is... well I just fixed it. So :smile:

**Comment by chrislitherland95** [comment]
Great, I'll give it a shot. What setting do you recommend for SVG export in illustrator so it's consistent with the Google SVG format? I couldn't see a way to force the export size..

**Comment by Templarian** [comment]
Not sure tbh, but let me know what doesn't work. Ideally I want the import to handle as many different variations as possible. The only thing I won't be supporting is more than 1 path in the SVG.

**Comment by chrislitherland95** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="24px" height="24px" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
<path d="M16,2H8C6.9,2,6,2.9,6,4v16c0,1.1,0.9,2,2,2h8c1.1,0,2-0.9,2-2V4C18,2.9,17.1,2,16,2z M15,20c-0.6,0-1-0.4-1-1s0.4-1,1-1
	s1,0.4,1,1S15.6,20,15,20z M16,10H8V8h8V10z M16,6H8V4h8V6z"/>
</svg>
```

The uploader is still upset. I think because illustrator adds "px" in the width & height declaration...You can toggle the width/height declaration with the "Reponsive" switch in the output dialog (under advanced). If responsive is unchecked, the size will be declared. If Responsive is checked, there will be no height/width declaration.

Hope that helps :)

**Comment by chrislitherland95** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     width="24" height="24" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
<path d="M16,2H8C6.9,2,6,2.9,6,4v16c0,1.1,0.9,2,2,2h8c1.1,0,2-0.9,2-2V4C18,2.9,17.1,2,16,2z M15,20c-0.6,0-1-0.4-1-1s0.4-1,1-1
    s1,0.4,1,1S15.6,20,15,20z M16,10H8V8h8V10z M16,6H8V4h8V6z"/>
</svg>
```

Even with it declared, still won't accept it. I'm no good with Regex, so it looks fine to me...

**Comment by Templarian** [comment]
Sorry, was eating dinner there. Fixed. I forgot the flag so the period matched multiple lines. Oversight on my part. Good bug find! It works by the way. I tested your file.

**Comment by Templarian** [comment]
By the way, I'm coding another error message to let users know they need to unite all their paths before importing. That will be in tonight.

**Comment by danielhickman** [comment]
I'd just copy out the one path and put in what you see at the beginning of
the ones already on the site.

**Comment by Templarian** [comment]
@danielhickman Ha. It only takes me a few minutes to fix. Alpha testing is all about reporting these bugs to me not working around them. :stuck_out_tongue_closed_eyes:

**Comment by chrislitherland95** [comment]
Yeah I figured I could work around it but that's not really in the spirit of user design :+1:

**Comment by chrislitherland95** [comment]
@Templarian sorry to keep the issue going, but is the contribution section disabled for some reason? The title says (disabled) and after I upload the first icon, I am unable to progress to the next 4 as the section is greyed out and will not accept input....will it be enabled back soon? :smile:

**Comment by Templarian** [comment]
Yea, just create an issue with a catchy title like. "I want to be a contributor." Include a few SVG files and I'll add you to the system.

I had to disable the form because it isn't that well coded right now. Technically the way it is suppose to work is users submit 5 icons and contributors can vote on the icons (up/down). If 3 of the users icons get through the process they are sent an invitation to join the contributor team.

My focus became more aimed at the end users as _many_ people are now using the webfont in their projects and I need to create a better experience for new users (SASS, LESS, custom webfont packaging). Simply downloading individual icons is fine, but I want to say a majority want that webfont.

**Comment by chrislitherland95** [comment]
Oh Sure. I have used a lot of icons from your site in my project, and I wanted to give something back is all. Some of the icons needed I could not find so I made them myself, but I am happy to make requests as this is an excellent resource! :+1:

**Comment by Templarian** [comment]
Yea, just show me 3 svg icons of your favorites and I'll send you an invite. Just need to make sure the are consistent with the others. 2px rounded edges 2px widths on all lines 2px spacing on lines. Clearly visible contrast between black and whitespace.

As long as they follow that and are recognizable I'll send the invite right away.
